#!/usr/bin/env python3
"""Generate src/themes.rs from Omarchy's theme colors.toml files (see emit())."""
import glob, os, re, sys
def parse(path):
    raw = {}
    for line in open(path):
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line: continue
        k, v = line.split('=', 1); raw[k.strip()] = v.strip().strip('"')
    aliases = [("background",["bg","color0"]),("dark_background",["dark_bg"]),("darker_background",["darker_bg"]),("lighter_background",["lighter_bg"]),("foreground",["fg","color7"]),("dark_foreground",["dark_fg","color8"]),("light_foreground",["light_fg"]),("bright_foreground",["bright_fg","color15"]),("red",["color1"]),("green",["color2"]),("yellow",["color3"]),("blue",["color4"]),("magenta",["purple","color5"]),("cyan",["color6"]),("bright_red",["color9"]),("bright_green",["color10"]),("bright_yellow",["color11"]),("bright_blue",["color12"]),("bright_magenta",["bright_purple","color13"]),("bright_cyan",["color14"])]
    for canon, alts in aliases:
        if canon not in raw:
            for a in alts:
                if a in raw: raw[canon] = raw[a]; break
    return raw
def hexrgb(v):
    m = re.fullmatch(r'#?([0-9a-fA-F]{6})', v.strip())
    return tuple(int(m.group(1)[i:i+2], 16) for i in (0, 2, 4)) if m else None
def mix(a, b, t):
    return tuple(int((x + (y - x) * t) + 0.5) for x, y in zip(a, b))
WHITE = (255, 255, 255)
def palette(raw):
    g = lambda k: hexrgb(raw[k]) if k in raw and hexrgb(raw[k]) else None
    bg, fg = g("background"), g("foreground")
    if not bg or not fg: return None
    bright_fg = g("bright_foreground") or fg
    dark_fg = g("dark_foreground") or fg
    muted = g("muted") or dark_fg
    hue = lambda k: g(k) or fg
    red, green, yellow, blue, magenta, cyan = hue("red"), hue("green"), hue("yellow"), hue("blue"), hue("magenta"), hue("cyan")
    br = lambda k, base: g(k) or mix(base, WHITE, 0.2)
    base16 = [bg, red, green, yellow, blue, magenta, cyan, fg, muted,
              br("bright_red", red), br("bright_green", green), br("bright_yellow", yellow),
              br("bright_blue", blue), br("bright_magenta", magenta), br("bright_cyan", cyan), bright_fg]
    mode = raw.get("mode") or raw.get("theme_type")
    light = (mode == "light") if mode else (sum(bg) > 382)
    return dict(base16=base16, fg=fg, bg=bg, cursor=bright_fg, light=light)
out = {}
for p in (sorted(glob.glob("*.toml")) if len(sys.argv) == 1 else []):
    name = os.path.basename(p)[:-5]
    pal = palette(parse(p))
    if pal: out[name] = pal
    else: print("SKIP", name, file=sys.stderr)
if __name__ == "__main__" and len(sys.argv) == 1:
    tn = out["tokyo-night"]
    print("tokyo-night base16:", " ".join("#%02x%02x%02x" % c for c in tn["base16"]))
    print(len(out), "palettes")

# ---- emit src/themes.rs -------------------------------------------------
# usage: python3 tools/gen_themes.py <dir of omarchy themes/*.toml> <omarchy commit> > src/themes.rs
NAMES = {"rose-pine": "Rosé Pine", "retro-82": "Retro 82", "tokyo-night": "Tokyo Night"}
# Published palettes (MIT): Solarized (Ethan Schoonover) and Dracula.
CLASSICS = [
    ("solarized-dark", "Solarized Dark", False, "002b36 dc322f 859900 b58900 268bd2 d33682 2aa198 eee8d5 586e75 cb4b16 93a1a1 657b83 839496 6c71c4 2aa198 fdf6e3", "839496", "002b36", "93a1a1"),
    ("solarized-light", "Solarized Light", True, "fdf6e3 dc322f 859900 b58900 268bd2 d33682 2aa198 073642 93a1a1 cb4b16 586e75 657b83 839496 6c71c4 2aa198 002b36", "657b83", "fdf6e3", "586e75"),
    ("dracula", "Dracula", False, "21222c ff5555 50fa7b f1fa8c bd93f9 ff79c6 8be9fd f8f8f2 6272a4 ff6e6e 69ff94 ffffa5 d6acff ff92df a4ffff ffffff", "f8f8f2", "282a36", "f8f8f2"),
]
def emit(src_dir, commit):
    os.chdir(src_dir)
    pals = {}
    for p in sorted(glob.glob("*.toml")):
        pal = palette(parse(p))
        if pal: pals[os.path.basename(p)[:-5]] = pal
    h = lambda c: "0x%02x%02x%02x" % c
    print("//! Bundled terminal colour schemes. GENERATED by tools/gen_themes.py; do not edit.")
    print("//!")
    print("//! The Omarchy schemes come from omarchy@%s `themes/*/colors.toml`" % commit[:12])
    print("//! (github.com/omacom/omarchy, MIT, Copyright (c) David Heinemeier Hansson),")
    print("//! mapped to base16 exactly as the OctoSense shell does (Omarchy's alacritty")
    print("//! mapping: normal black = background … bright white = bright_foreground).")
    print("//! Solarized (Ethan Schoonover) and Dracula use their published palettes (MIT).")
    print()
    print("#[derive(Clone, Copy, Debug, PartialEq)]")
    print("pub struct Scheme {")
    print("    pub id: &'static str,")
    print("    pub name: &'static str,")
    print("    pub light: bool,")
    print("    pub base16: [u32; 16],")
    print("    pub foreground: u32,")
    print("    pub background: u32,")
    print("    pub cursor: u32,")
    print("}")
    print()
    print("pub const SCHEMES: &[Scheme] = &[")
    for sid, pal in pals.items():
        name = NAMES.get(sid, sid.replace("-", " ").title())
        print('    Scheme { id: "%s", name: "%s", light: %s, base16: [%s], foreground: %s, background: %s, cursor: %s },' % (
            sid, name, "true" if pal["light"] else "false", ", ".join(h(c) for c in pal["base16"]),
            h(pal["fg"]), h(pal["bg"]), h(pal["cursor"])))
    for sid, name, light, b16, fg, bg, cur in CLASSICS:
        print('    Scheme { id: "%s", name: "%s", light: %s, base16: [%s], foreground: 0x%s, background: 0x%s, cursor: 0x%s },' % (
            sid, name, "true" if light else "false", ", ".join("0x" + x for x in b16.split()), fg, bg, cur))
    print("];")
    print()
    print("/// The scheme with this id, if bundled.")
    print("pub fn find(id: &str) -> Option<&'static Scheme> {")
    print("    SCHEMES.iter().find(|s| s.id == id)")
    print("}")

if __name__ == "__main__" and len(sys.argv) == 3:
    emit(sys.argv[1], sys.argv[2])
